language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
gemfile:
  - gemfiles/rails30_paperclip23.gemfile
  - gemfiles/rails30_paperclip2x.gemfile
  - gemfiles/rails30_paperclip30.gemfile
  - gemfiles/rails30_paperclip3x.gemfile
  - gemfiles/rails31_paperclip23.gemfile
  - gemfiles/rails31_paperclip2x.gemfile
  - gemfiles/rails31_paperclip30.gemfile
  - gemfiles/rails31_paperclip3x.gemfile
  - gemfiles/rails32_paperclip23.gemfile
  - gemfiles/rails32_paperclip2x.gemfile
  - gemfiles/rails32_paperclip30.gemfile
  - gemfiles/rails32_paperclip3x.gemfile
  - gemfiles/rails32_paperclip40.gemfile
  - gemfiles/rails32_paperclip4x.gemfile
  - gemfiles/rails40_paperclip42.gemfile
  - gemfiles/rails40_paperclip4x.gemfile
